MealPlanner365/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MealPlanner365.Models;
using MealPlanner365.Models.ViewModels;
using MealPlanner365.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace MealPlanner365.Controllers
{
    [Authorize]
    public class SettingsController : Controller
    {
        private readonly ISettingsRepository settingsRepository;
        private readonly IOptionsSnapshot<MealPlanSettings> settings;

        public SettingsController(ISettingsRepository settingsRepository, IOptionsSnapshot<MealPlanSettings> settings)
        {
            this.settingsRepository = settingsRepository;
            this.settings = settings;
        }

        public async Task<IActionResult> Index(Guid mealPlanId)
        {
            ViewData["MealPlan"] = mealPlanId;

            var diners = await settingsRepository.GetMealPlanDiners(mealPlanId);

            var userViewModel = new List<UserViewModel>();

            foreach (var diner in diners)
            {
                userViewModel.Add(new UserViewModel()
                {
                    UserId = diner.Id,
                    Name = diner.UserName,
                    EmailConfirmed = diner.EmailConfirmed,
                    LockedOut = diner.LockoutEnabled,
                    Administrator = await settingsRepository.IsAdministrator(diner.Id)
                });
            }

            var mealPlanSettings = new SettingsViewModel()
            {
                Url = settings.Value.Url,
                DisplayDays = settings.Value.DisplayDays,
                PageIncrements = settings.Value.PageIncrements,
                Diners = userViewModel
            };

            return View(mealPlanSettings);
        }
    }
}

MealPlanner365/Views/Shared/_AdminTabs.cshtml
<ul class="nav nav-tabs card-header-tabs" id="tab-list" role="tablist">
    <li class="nav-item">
        <a active-url="Item" asp-controller="Item" asp-action="@ViewData["MealPlan"]" class="nav-link text-dark" role="tab" aria-controls="Items" aria-selected="false">Items</a>
    </li>
    <li class="nav-item">
        <a active-url="Category" asp-controller="Category" asp-action="@ViewData["MealPlan"]" class="nav-link text-dark" role="tab" aria-controls="Categories" aria-selected="false">Categories</a>
    </li>
    <li class="nav-item">
        <a active-url="Meal" asp-controller="Meal" asp-action="@ViewData["MealPlan"]" class="nav-link text-dark" role="tab" aria-controls="Meals" aria-selected="false">Meals</a>
    </li>
    <li class="nav-item">
        <a active-url="Shopping" asp-controller="Shopping" asp-action="@ViewData["MealPlan"]" class="nav-link text-dark" role="tab" aria-controls="Shopping" aria-selected="false">Shopping</a>
    </li>
</ul>

MealPlanner365/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Meal Planner 365</title>
    <link rel="stylesheet" href="~/css/custom-bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-select/dist/css/bootstrap-select.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-dark bg-dark box-shadow">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand display-4" asp-controller="Home" asp-action="Index">Meal Planner</a>
                <div class="navbar-collapse collapse">
                    <partial name="_NavbarOptions" />
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <footer class="border-top footer small bg-dark text-light">
        <div class="container d-flex">
            <div>&copy; @DateTime.Now.Year | Meal Planner 365 | <a class="text-light" asp-controller="Shared" asp-action="Privacy">Privacy</a> | <a class="text-light" asp-controller="Shared" asp-action="TermsAndConditions">Terms of Use</a></div>
            <a class="ml-auto text-light" href="https://github.com/ade-palmer/mealplanner.core" rel="noopener noreferrer" target="_blank">Github<i class="fab fa-github pl-2"></i></a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

    @*FontAwesome CSS - loading last, so it doesn't block rendering*@
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

</body>
</html>

MealPlanner365/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Meal Planner 365</title>
    <link rel="stylesheet" href="~/css/custom-bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-select/dist/css/bootstrap-select.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand display-4" asp-controller="Home" asp-action="Index">Meal Planner</a>
                <div class="navbar-collapse collapse">
                    <partial name="_NavbarOptions" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer small bg-dark text-light">
        <div class="container d-flex">
            <div>&copy; @DateTime.Now.Year | Meal Planner 365 | <a class="text-light" asp-controller="Shared" asp-action="Privacy">Privacy</a> | <a class="text-light" asp-controller="Shared" asp-action="TermsAndConditions">Terms of Use</a></div>
            <a class="ml-auto text-light" href="https://github.com/ade-palmer/mealplanner.core" rel="noopener noreferrer" target="_blank">Github<i class="fab fa-github pl-2"></i></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

    @*FontAwesome CSS - loading last, so it doesn't block rendering*@
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

</body>
</html>

MealPlanner365/Views/Shared/_NavbarOptions.cshtml
@inject SignInManager<ApplicationUser> signInManager
@{
    bool isSignedIn = signInManager.IsSignedIn(User);
}

    <ul class="navbar-nav">
        @if (@ViewData["MealPlan"] != null)
        {
            <li class="nav-item">
                <a class="nav-link text-light" asp-controller="MealPlan" asp-action="@ViewData["MealPlan"]"><i class="fas fa-calendar-day" style="width: 30px;"></i><span>Today</span></a>
            </li>
            <li class="nav-item"><hr class="border-top border-secondary"></li>
            <li class="nav-item">
                <a class="nav-link text-light" asp-controller="Item" asp-action="@ViewData["MealPlan"]"><i class="fas fa-hamburger" style="width: 30px;"></i><span>Items</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" asp-controller="Meal" asp-action="@ViewData["MealPlan"]" asp-route-tab="meals"><i class="fas fa-utensils" style="width: 30px;"></i><span>Meals</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" asp-controller="Settings" asp-action="@ViewData["MealPlan"]" asp-route-tab="diners"><i class="fas fa-users" style="width: 30px;"></i><span>Diners</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light" asp-controller="Shopping" asp-action="@ViewData["MealPlan"]"><i class="fas fa-shopping-basket" style="width: 30px;"></i><span>Shopping</span></a>
            </li>
        }
        <li class="nav-item"><hr class="border-top border-secondary"></li>
        <li class="nav-item">
            <a class="nav-link text-light" asp-controller="Settings" asp-action="@ViewData["MealPlan"]"><i class="fas fa-cog" style="width: 30px;"></i><span>Settings</span></a>
        </li>
        <li condition="!isSignedIn" class="nav-item">
            <a class="nav-link text-light" asp-controller="Account" asp-action="Login"><i class="fas fa-sign-in-alt" style="width: 30px;"></i><span>Login</span></a>
        </li>
        <li condition="isSignedIn" class="nav-item">
            <a class="nav-link text-light" asp-controller="Account" asp-action="Logout"><i class="fas fa-sign-out-alt" style="width: 30px;"></i><span>Logout (@User.Identity.Name)</span></a>
        </li>
    </ul>

MealPlanner365/Views/Shared/_StatusMessage.cshtml
@if (TempData["StatusMessage"] != null)
{
    var statusMessageClass = TempData["StatusMessage"].ToString().StartsWith("Warning") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible mt-3"  role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        @TempData["StatusMessage"]
    </div>
}